### PR TITLE
QTY-1102: Create PR template for canvas shim

### PR DESCRIPTION
**Pull request by CJAdeszko**

### CODE REVIEW

**Comment by dneighbors** [comment]
Bought time!

**Comment by CJAdeszko** [comment]
[QTY-1102](https://strongmind.atlassian.net/browse/QTY-1102)

## Purpose 
In order to provide better context for current and future engineers, add a pull request template (following the structure of this comment) to canvas-enterprise in the shim, lms, and docker repositories starting with the shim. 

## Approach 
Add `pull_request_template.md` to the `.github` directory of the shim

## Testing
n/a

## Screenshots (if applicable)
n/a

## Anything else 
Hopefully this will help standardize the pull request process to provide better context about our changes and stimulate discussion and learning amongst engineers during the PR process

**Comment by CJAdeszko** [comment]
@cpython1234 this is what the template would look like ^

**Comment by adiaz04** [comment]
Closing as we moved this to the culture repo.

**Pull request closed without merging**
